korin:
  monster_zokusei: "cfire"
  unit_zokusei: "yugarabo_json/mizu"
  s0: "打撃"
  s1: "銃撃"
  monsterASS: 4

unit_syozi:
  xlsxname: "20211204_所持確認表"

zyoui_rune:
  hunter: [35, 33, 32.863, 32.591]
  foser: [35, 33.650, 33, 33, 31.600, 27.066]
  syuter: [35, 33, 32.947]

unitGUTS: 12
runeATK: 0.35
runeHIGH: 0.35
unitB: 0
unitHOSEI: 1
mindYURI: 0
mindOMAKE: 0
runeZOKUSEI: 0
seedBREAK: 0
runeICHRYS: 0
runeENHANCER: 0
seedSOUL: 0
flagSPECIAL: 0

