# 毎回変えるところはここになるのかな
korin:
  # モンスターの属性
  monster_zokusei: "cdark"
  # 参照するjson ユニットの属性表に書き込んだやつを使う
  unit_zokusei: "yugarabo_json/light"
  # 特攻の武器種
  s0: "斬撃"
  s1: "銃撃"
  # モンスター部位数
  monster_V: 4

# 所持表の名前を変えるならここ
# 所持状況書き込み後もここを参照するのでseet_splitterを複数回呼ぶのはやめたほうがいい
unit_syozi:
  xlsxname: "sheets/light"
  simulation_data: "npz/20220528_降臨1日目"
  pickup: 32
